Support XCH fee
richardkiss/chiaswap pull request #5
Opened 2022-04-28 16:39 UTC by kimsk

This is to resolve the issue https://github.com/richardkiss/chiaswap/issues/3 regarding XCH fee support.

Basically, I add another `input` to capture the fee amount and pass them around accordingly. I have tested with `clean`, `clawback`, and `sweep` cases.

2022-04-28 16:41 UTC, kimsk commented on SConstruct
> +py_source = Glob("chiaswap/*.py") + Glob("chiaswap/*.clsp")
I think `clsp` is the official `Chialisp` extension, right?

2022-04-28 16:43 UTC, kimsk commented on chiaswap/main.py
> +    fee_amount = Decimal(input("> ") or "0.00005")
Adding another input asking for fee amount. The XCH side has to send `xch_amount + fee_amount` to create the coin with the `p2_delayed_or_preimage`.

2022-04-28 16:44 UTC, kimsk commented on chiaswap/main.py
> +    print(f"go into your XCH wallet and send {xch_amount + fee_amount} XCH to")
The XCH side has to send `xch_amount + fee_amount` to create the coin with the `p2_delayed_or_preimage` puzzle.

2022-04-28 16:47 UTC, kimsk commented on chiaswap/main.py
>      conditions = [[51, clawback_puzzle_hash, xch_amount_mojos]]
`CREATE_COIN` with `xch_amount_mojos` (not including fee amount).

2023-02-14 17:40 UTC, richardkiss commented on chiaswap/main.py
> +            "Enter your counter-party private key OR the lightning invoice receipt pre-image or `quit`"
A cursory Google search suggests that "counterparty" is a word and that it makes sense here.

2023-02-14 17:41 UTC, richardkiss commented on chiaswap/main.py
> +    print("Your counter-party should share their (disposable) private key")
Ditto.

2023-02-14 17:42 UTC, richardkiss requested changes
Undo the "counterparty" changes and I'll merge. Sound good?

Sorry for the delay.

2023-02-14 18:05 UTC, kimsk commented
> Undo the "counterparty" changes and I'll merge. Sound good?

Undo, and I also notice coupIe more places using `counter-party`, so I changed them all to counterparty.

2023-02-15 05:50 UTC, richardkiss commented
> > Undo the "counterparty" changes and I'll merge. Sound good?
> 
> Undo, and I also notice coupIe more places using `counter-party`, so I changed them all to counterparty.

Ha, thanks for this consistency improvement.

2023-02-15 05:51 UTC, merged